
ALTER TABLE reminders DROP CONSTRAINT reminders_pkey;
ALTER TABLE reminders DROP COLUMN message_id;
ALTER TABLE reminders ADD COLUMN user_id VARCHAR ( 30 ) DEFAULT "0";   
ALTER TABLE reminders ADD COLUMN id SERIAL PRIMARY KEY;
