name: OAF
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable corepack
        run: corepack enable
      - name: Install modules
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      - name: Run type check
        run: yarn tsc
